// Paleta oficial do protótipo — warm_culinary (prototipo_projetohibrido_receitas/warm_culinary/DESIGN.md)
// Paprika #AB3500 como acento, fundo cool-neutral #F8F9FF
export const cores = {
  primary: "#AB3500",
  primaryHover: "#832600",
  onPrimary: "#FFFFFF",
  primaryContainer: "#FF6B35",
  onPrimaryContainer: "#5F1900",
  primaryFixed: "#FFDBD0",
  primaryFixedDim: "#FFB59D",
  onPrimaryFixed: "#390C00",
  onPrimaryFixedVariant: "#832600",

  background: "#F8F9FF",
  onBackground: "#151C26",
  surface: "#F8F9FF",
  onSurface: "#151C26",
  onSurfaceVariant: "#594139",
  surfaceVariant: "#DCE3F2",
  surfaceDim: "#D3DAE9",
  surfaceBright: "#F8F9FF",
  surfaceContainer: "#E7EEFD",
  surfaceContainerLow: "#EFF3FF",
  surfaceContainerLowest: "#FFFFFF",
  surfaceContainerHigh: "#E2E8F7",
  surfaceContainerHighest: "#DCE3F2",
  surfaceTint: "#AB3500",

  secondary: "#5D5E61",
  onSecondary: "#FFFFFF",
  secondaryContainer: "#E0DFE3",
  onSecondaryContainer: "#616265",
  secondaryFixed: "#E2E2E5",
  secondaryFixedDim: "#C6C6C9",
  onSecondaryFixed: "#1A1C1E",
  onSecondaryFixedVariant: "#45474A",
  tertiary: "#444748",
  onTertiary: "#FFFFFF",
  tertiaryContainer: "#5C5F60",
  onTertiaryContainer: "#D7D9DA",
  tertiaryFixed: "#E1E3E4",
  tertiaryFixedDim: "#C5C7C8",
  onTertiaryFixed: "#191C1D",
  onTertiaryFixedVariant: "#444748",

  outline: "#8D7168",
  outlineVariant: "#E1BFB5",
  outlineWarm: "#8D7168",
  error: "#BA1A1A",
  onError: "#FFFFFF",
  errorContainer: "#FFDAD6",
  onErrorContainer: "#93000A",

  inverseSurface: "#2A313C",
  inverseOnSurface: "#EBF1FF",
  inversePrimary: "#FFB59D",

  star: "#FFB02E",
  warmSurface: "#F8F9FF",
} as const;

export type Cores = typeof cores;